// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzjMVKfPF0Hra2Ix_tXANth9vwhyUM4Y8',
    appId: '1:340074484133:web:80d1ae29683d3cb434184c',
    messagingSenderId: '340074484133',
    projectId: 'chatapp-87cc5',
    authDomain: 'chatapp-87cc5.firebaseapp.com',
    databaseURL: 'https://chatapp-87cc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-87cc5.appspot.com',
    measurementId: 'G-ZR6XLLE02V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNcgFajmLbfs98g76Fply-r4muLq-i84M',
    appId: '1:340074484133:android:f6bf1842e5437b6634184c',
    messagingSenderId: '340074484133',
    projectId: 'chatapp-87cc5',
    databaseURL: 'https://chatapp-87cc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-87cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMryz8Xv7JoKCZk_7BV3ARtriBCurtTQY',
    appId: '1:340074484133:ios:008fef7bef35ed8334184c',
    messagingSenderId: '340074484133',
    projectId: 'chatapp-87cc5',
    databaseURL: 'https://chatapp-87cc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-87cc5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMryz8Xv7JoKCZk_7BV3ARtriBCurtTQY',
    appId: '1:340074484133:ios:008fef7bef35ed8334184c',
    messagingSenderId: '340074484133',
    projectId: 'chatapp-87cc5',
    databaseURL: 'https://chatapp-87cc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-87cc5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzjMVKfPF0Hra2Ix_tXANth9vwhyUM4Y8',
    appId: '1:340074484133:web:9761dc395412571534184c',
    messagingSenderId: '340074484133',
    projectId: 'chatapp-87cc5',
    authDomain: 'chatapp-87cc5.firebaseapp.com',
    databaseURL: 'https://chatapp-87cc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-87cc5.appspot.com',
    measurementId: 'G-ZDZCMD2R2P',
  );
}
